apiVersion: apps/v1
kind: Deployment
metadata:
    name: cc-auth
spec:
    selector:
        matchLabels:
            app:
                cc-auth
    template:
        metadata:
            labels:
                app: cc-auth
        spec:
            containers:
                -   name: cc-auth
                    image: cc-auth:0.0.3
                    imagePullPolicy: Never # use local image
                    resources:
                        limits:
                            memory: "1024Mi"
                            cpu: "500m"
                    ports:
                        -   containerPort: 8081
                    env:
                        - name: DB_HOST
                          value: mysql
                        - name: DB_NAME
                          value: app_cc
                        - name: DB_USERNAME
                          value: root
                        - name: DB_PASSWORD
                          value: root
---
apiVersion: v1
kind: Service
metadata:
    name: auth-service
spec:
    type: LoadBalancer
    ports:
        - protocol: TCP 
          port: 8081 # port inside the cluster
          targetPort: 8081 # Port exposed to the oustside
    selector:
        app: cc-auth
