apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-fe
spec:
  selector:
    matchLabels:
      app: cc-fe
  replicas: 1
  template:
    metadata:
      labels:
        app: cc-fe
    spec:
      containers:
        - name: cc-fe
          image: cc-fe:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_SERVER_URL
              value: "http://localhost:1337"
---
apiVersion: v1
kind: Service
metadata:
  name: cc-fe-client-service
spec:
  type: LoadBalancer
  selector:
    app: cc-fe
  ports:
    - port: 3000
      targetPort: 3000


---
