apiVersion: apps/v1
kind: Deployment
metadata:
    name: cc-be
spec:
    selector:
        matchLabels:
            app:
                cc-be
    template:
        metadata:
            labels:
                app: cc-be
        spec:
            containers:
                -   name: cc-be
                    image: cc-be-api_service:latest
                    imagePullPolicy: Never # use local image
                    resources:
                        limits:
                            memory: "1024Mi"
                            cpu: "500m"
                    ports:
                        -   containerPort: 8080
                    env:
                        - name: DB_HOST
                          value: mysql
                        - name: DB_NAME
                          value: app_cc
                        - name: DB_USERNAME
                          value: root
                        - name: DB_PASSWORD
                          value: root
---
apiVersion: v1
kind: Service
metadata:
    name: api-service
spec:
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 1337 # port inside the cluster
          targetPort: 8080 # Port exposed to the oustside
    selector:
        app: cc-be
