apiVersion: apps/v1
kind: Deployment
metadata:
    name: cc-db
spec:
    selector:
        matchLabels:
            app:
                cc-db
    template:
        metadata:
            labels:
                app: cc-db
        spec:
            containers:
                -   name: cc-db
                    image: cc-be-api_service:latest
                    imagePullPolicy: Never # use local image
                    resources:
                        limits:
                            memory: "128Mi"
                            cpu: "500m"
                    ports:
                        -   containerPort: 3307