apiVersion: apps/v1
kind: Deployment
metadata:
    name: cc-be
spec:
    selector:
        matchLabels:
            app:
                cc-be
    template:
        metadata:
            labels:
                app: cc-be
        spec:
            containers:
                -   name: cc-be
                    image: mysql:8.0
                    imagePullPolicy: Never # use local image
                    resources:
                        limits:
                            memory: "128Mi"
                            cpu: "500m"
                    ports:
                        -   containerPort: 8080